import { login } from "./login.js";

const run = async () => {
  const client = await login();

  const clients = await client.get("/api/client/list");
  const products = await client.get("/api/product/list");

  const cust = clients.data.result[0];
  const prod = products.data.result[0];

  const invoicePayload = {
    clientId: cust._id,
    items: [
      {
        productId: prod._id,
        quantity: 2,
        price: prod.salePrice
      }
    ],
    invoiceNote: "Generated by script"
  };

  const res = await client.post("/api/invoice/create", invoicePayload);
  console.log("Created Invoice:", res.data.result._id);
};

run();
